spring.application.name=shift-control

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/shift_control
spring.datasource.username=shift_control_user
spring.datasource.password=shift_control_password

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=true
spring.jpa.open-in-view=false

# ===============================
# SERVER
# ===============================

server.port=8080